apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: translator-hpa
  namespace: translator
  labels:
    app: translator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: translator-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70