apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-translator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AhmeFawzy/flask_translator.git
    targetRevision: testing
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: translator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true